import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import dynamic from 'next/dynamic'
import RadarChartGraph from '@/components/radar-chart'
import { ResponsiveContainer } from 'recharts'
const Graph = dynamic(import('../../components/bar-chart'), { ssr: false })
const Radar = dynamic(import('../../components/radar-chart'), { ssr: false })
const Pie = dynamic(import('../../components/pie-chart'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export default function GraphPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className={`${styles.className} ${inter.className}`}>
        <ResponsiveContainer>
          <Pie />
        </ResponsiveContainer>
      </main>
    </>
  )
}
