const data = [
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Principal Data Scientist',
    salary: '80000',
    salary_currency: 'EUR',
    salary_in_usd: '85847',
    employee_residence: 'ES',
    remote_ratio: '100',
    company_location: 'ES',
    company_size: 'L',
  },
  {
    work_year: '2023',
    experience_level: 'MI',
    employment_type: 'CT',
    job_title: 'ML Engineer',
    salary: '30000',
    salary_currency: 'USD',
    salary_in_usd: '30000',
    employee_residence: 'US',
    remote_ratio: '100',
    company_location: 'US',
    company_size: 'S',
  },
  {
    work_year: '2023',
    experience_level: 'MI',
    employment_type: 'CT',
    job_title: 'ML Engineer',
    salary: '25500',
    salary_currency: 'USD',
    salary_in_usd: '25500',
    employee_residence: 'US',
    remote_ratio: '100',
    company_location: 'US',
    company_size: 'S',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '175000',
    salary_currency: 'USD',
    salary_in_usd: '175000',
    employee_residence: 'CA',
    remote_ratio: '100',
    company_location: 'CA',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '120000',
    salary_currency: 'USD',
    salary_in_usd: '120000',
    employee_residence: 'CA',
    remote_ratio: '100',
    company_location: 'CA',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Applied Scientist',
    salary: '222200',
    salary_currency: 'USD',
    salary_in_usd: '222200',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'L',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Applied Scientist',
    salary: '136000',
    salary_currency: 'USD',
    salary_in_usd: '136000',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'L',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '219000',
    salary_currency: 'USD',
    salary_in_usd: '219000',
    employee_residence: 'CA',
    remote_ratio: '0',
    company_location: 'CA',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '141000',
    salary_currency: 'USD',
    salary_in_usd: '141000',
    employee_residence: 'CA',
    remote_ratio: '0',
    company_location: 'CA',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '147100',
    salary_currency: 'USD',
    salary_in_usd: '147100',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Scientist',
    salary: '90700',
    salary_currency: 'USD',
    salary_in_usd: '90700',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Analyst',
    salary: '130000',
    salary_currency: 'USD',
    salary_in_usd: '130000',
    employee_residence: 'US',
    remote_ratio: '100',
    company_location: 'US',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Analyst',
    salary: '100000',
    salary_currency: 'USD',
    salary_in_usd: '100000',
    employee_residence: 'US',
    remote_ratio: '100',
    company_location: 'US',
    company_size: 'M',
  },
  {
    work_year: '2023',
    experience_level: 'EN',
    employment_type: 'FT',
    job_title: 'Applied Scientist',
    salary: '213660',
    salary_currency: 'USD',
    salary_in_usd: '213660',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'L',
  },
  {
    work_year: '2023',
    experience_level: 'EN',
    employment_type: 'FT',
    job_title: 'Applied Scientist',
    salary: '130760',
    salary_currency: 'USD',
    salary_in_usd: '130760',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'L',
  },
  {
    work_year: '2023',
    experience_level: 'SE',
    employment_type: 'FT',
    job_title: 'Data Modeler',
    salary: '147100',
    salary_currency: 'USD',
    salary_in_usd: '147100',
    employee_residence: 'US',
    remote_ratio: '0',
    company_location: 'US',
    company_size: 'M',
  },
]

export default data
